service: s3-upload

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-1
plugins:
 -serverless-iam-roles-per-function 

custom:
  fileUploadBucketName: ${self:service}-bucket-${self:provider.stage}
functions:
s3Upload:
 handler: src/upload.handler
 name: s3-upload
 description: A lamda Handler to upload file to s3 bucket 
 timeout: 60 # sec
 memmorysize: 128 #mb
 events:
  -http:
    path: images
    method: POST
iamRoleStatements: 
 - Effect: Allow
   Action:
   -"s3:Put*"
   Resource: arn:aws:s3:::${self.custome.fileUploadBucketName}/*
enviroment:
FILE_UPLOAD_BUCKET_NAME:${self.custome.fileUploadBucketName}


resources:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.fileUploadBucketName}
        AccessControl: PublicRead